export const UPDATE_MOVIES = "UPDATE_MOVIES";
export const SET_CURRENT_MOVIE = "SET_CURRENT_MOVIE";
export const LOADING = "LOADING";
export const ADD_NOMINATION = "ADD_NOMINATION";
export const REMOVE_NOMINATION = "REMOVE_NOMINATION";
export const UPDATE_NOMINATION = "UPDATE_NOMINATION";